<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Blitzy.LegacyPort.UserApp</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blitzy.LegacyPort.Core\Blitzy.LegacyPort.Core.csproj" />
  </ItemGroup>

</Project>
